In [20]:
import pandas as pd

df = pd.read_csv('../data/News Articles/processed/Bloomberg_with_scores.csv', encoding='ISO-8859-1', index_col='Date')
df.index = pd.to_datetime(df.index)
df = df.sort_index()

In [24]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Unnamed: 0processed_text', 'Headline',
       'Unnamed: 0text', 'text', 'distilbert_score', 'svc_score', 'gbdt_score',
       'knn_score', 'vader_score'],
      dtype='object')

In [34]:
import datetime as dt

cols = ['distilbert_score', 'svc_score', 'gbdt_score',
       'knn_score', 'vader_score']
df1 = df.copy()[cols]

df1 = df1.groupby(df1.index.date).mean()
print(df1)

            distilbert_score  svc_score  gbdt_score  knn_score  vader_score
2006-10-20         -0.989200  -1.000000   -1.000000  -1.000000     0.000000
2006-10-21         -0.982000  -1.000000   -1.000000  -1.000000     0.000000
2006-10-23         -0.899350  -1.000000   -1.000000  -1.000000    -0.074150
2006-10-24         -0.477450  -1.000000   -1.000000  -1.000000    -0.061475
2006-10-25          0.020350   0.000000   -1.000000   0.000000     0.321350
...                      ...        ...         ...        ...          ...
2013-11-22         -0.404322  -0.696379   -0.922006  -0.743733    -0.007557
2013-11-23         -0.469547  -0.794118   -0.882353  -0.897059     0.004715
2013-11-24         -0.169107  -0.536585   -1.000000  -0.780488     0.068910
2013-11-25         -0.407741  -0.689231   -0.926154  -0.726154     0.011150
2013-11-26         -0.459448  -0.696970   -0.939394  -0.666667     0.029139

[1915 rows x 5 columns]

In [32]:
df_daily = pd.read_csv('../data/Stock Data/SPY_2006_2013_daily.csv', index_col='Date')
df_daily.index = pd.to_datetime(df_daily.index)

In [42]:
df1['Close'] = df1.index.map(df_daily['Close'])

df1['3d'] = (df1.index + pd.Timedelta(days=3)).map(df_daily['Close']) - (df1.index + pd.Timedelta(days=4)).map(df_daily['Close'])
df1['9d'] = (df1.index + pd.Timedelta(days=9)).map(df_daily['Close']) - (df1.index + pd.Timedelta(days=12)).map(df_daily['Close'])
df1['15d'] = (df1.index + pd.Timedelta(days=15)).map(df_daily['Close']) - (df1.index + pd.Timedelta(days=20)).map(df_daily['Close'])
df1['1m'] = (df1.index + pd.Timedelta(days=30)).map(df_daily['Close']) - (df1.index + pd.Timedelta(days=40)).map(df_daily['Close'])
df1['2m'] = (df1.index + pd.Timedelta(days=60)).map(df_daily['Close']) - (df1.index + pd.Timedelta(days=80)).map(df_daily['Close'])
df1['3m'] = (df1.index + pd.Timedelta(days=90)).map(df_daily['Close']) - (df1.index + pd.Timedelta(days=120)).map(df_daily['Close'])

df1

,distilbert_score,svc_score,gbdt_score,knn_score,vader_score,Close,3d,9d,15d,1m,2m,3m
2006-10-20,-0.989200,-1.000000,-1.000000,-1.000000,0.000000,1368.599976,-0.359985,NaN,NaN,NaN,12.710083,NaN
2006-10-21,-0.982000,-1.000000,-1.000000,-1.000000,0.000000,NaN,-4.839966,10.590088,NaN,-0.130005,11.420044,NaN
2006-10-23,-0.899350,-1.000000,-1.000000,-1.000000,-0.074150,1377.020020,11.739990,NaN,NaN,NaN,-13.059937,NaN
2006-10-24,-0.477450,-1.000000,-1.000000,-1.000000,-0.061475,1377.380005,NaN,NaN,1.299927,NaN,NaN,-34.680054
2006-10-25,0.020350,0.000000,-1.000000,0.000000,0.321350,1382.219971,NaN,-15.479980,-14.890015,-8.170044,NaN,-28.390015
...,...,...,...,...,...,...,...,...,...,...,...,...
2013-11-22,-0.404322,-0.696379,-0.922006,-0.743733,-0.007557,1804.760010,-0.270020,NaN,NaN,NaN,43.960083,NaN
2013-11-23,-0.469547,-0.794118,-0.882353,-0.897059,0.004715,NaN,-4.479980,15.869995,NaN,-3.989990,25.109985,NaN
2013-11-24,-0.169107,-0.536585,-1.000000,-0.780488,0.068910,NaN,NaN,-9.939941,NaN,1.949951,9.199951,NaN
2013-11-25,-0.407741,-0.689231,-0.926154,-0.726154,0.011150,1802.479980,NaN,NaN,NaN,NaN,-39.539917,NaN
2013-11-26,-0.459448,-0.696970,-0.939394,-0.666667,0.029139,1802.750000,NaN,NaN,-4.320068,NaN,NaN,-4.950073

In [43]:
df1.columns

Index(['distilbert_score', 'svc_score', 'gbdt_score', 'knn_score',
       'vader_score', 'Close', '3d', '9d', '15d', '1m', '2m', '3m'],
      dtype='object')

In [53]:
# List of topic columns (manually extracted)
topic_cols = [
    'cluster', 'Climate & Environment', 'Consumer & Retail', 'Corporate Sector',
    'Crypto & Digital Assets', 'Education & Knowledge', 'Energy & Commodities',
    'Financial Markets', 'Geopolitics & Policy', 'Health & Biotech',
    'Legal & Regulation', 'Macro Finance', 'Real Estate & Housing',
    'Society & Labor', 'Tech & Innovation', 'Transport & Logistics', 'Uncertain'
]

sentiment_cols = ['distilbert_score', 'svc_score',
       'gbdt_score', 'knn_score', 'vader_score']

# Close price column
close_col = ['Close']

# Time horizon columns
horizon_cols = ['3d', '9d', '15d', '1m', '2m', '3m']

# Dictionary to store each mini-DataFrame
mini_dfs = {}

for h in horizon_cols:

    # Build mini_df without including `h` or `close_col` directly
    mini_df = df1[sentiment_cols + [h]].copy()
    mini_df['price_diff'] = df1[h].copy()

    mini_dfs[h] = mini_df

In [54]:
import statsmodels.api as sm
from scipy.stats import pearsonr
import pandas as pd

# Store output
summary_stats = []

for horizon, mini_df in mini_dfs.items():
    df_reg = mini_df.dropna()

    X = df_reg[sentiment_cols]
    y = df_reg['price_diff']

    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit()
    y_pred = model.fittedvalues
    corr, _ = pearsonr(y, y_pred)
    
    for col in sentiment_cols:
        summary_stats.append({
            'horizon': horizon,
            'r_squared': model.rsquared,
            'correlation': corr,
            'variable': col,
            'coef': model.params[col],
            't_stat': model.tvalues[col],
            'p_value': model.pvalues[col],
        })

summary_df = pd.DataFrame(summary_stats)

# Save to CSV
summary_df.to_csv('../data\Results Charts Models/trump_linear_regression_summary_3to1.csv', index=False)

# Also print for quick check
print(summary_df.round(4))

   horizon  r_squared  correlation          variable     coef  t_stat  p_value
0       3d     0.0042       0.0645  distilbert_score  -0.8929 -0.7828   0.4339
1       3d     0.0042       0.0645         svc_score  -0.6212 -0.4017   0.6880
2       3d     0.0042       0.0645        gbdt_score  -1.0636 -0.3823   0.7023
3       3d     0.0042       0.0645         knn_score  -1.7817 -1.1367   0.2560
4       3d     0.0042       0.0645       vader_score   2.7867  0.9528   0.3410
5       9d     0.0049       0.0698  distilbert_score   0.1770  0.0887   0.9294
6       9d     0.0049       0.0698         svc_score  -1.2718 -0.5218   0.6020
7       9d     0.0049       0.0698        gbdt_score  -3.6340 -0.6061   0.5447
8       9d     0.0049       0.0698         knn_score   3.8125  1.5198   0.1291
9       9d     0.0049       0.0698       vader_score   1.6361  0.3384   0.7352
10     15d     0.0060       0.0775  distilbert_score  -0.7243 -0.4121   0.6804
11     15d     0.0060       0.0775         svc_score  -1.2951 -0.6320   0.5276
12     15d     0.0060       0.0775        gbdt_score  -3.1628 -0.8349   0.4040
13     15d     0.0060       0.0775         knn_score  -3.0348 -1.5513   0.1212
14     15d     0.0060       0.0775       vader_score   2.3795  0.5604   0.5754
15      1m     0.0102       0.1012  distilbert_score  -3.9875 -1.1647   0.2446
16      1m     0.0102       0.1012         svc_score  -2.5382 -0.5981   0.5500
17      1m     0.0102       0.1012        gbdt_score  15.9179  1.3705   0.1710
18      1m     0.0102       0.1012         knn_score   7.0434  1.6824   0.0930
19      1m     0.0102       0.1012       vader_score  -4.6857 -0.5654   0.5720
20      2m     0.0056       0.0747  distilbert_score   1.3845  0.3928   0.6946
21      2m     0.0056       0.0747         svc_score   2.7307  0.5986   0.5496
22      2m     0.0056       0.0747        gbdt_score  -2.3653 -0.2725   0.7853
23      2m     0.0056       0.0747         knn_score   0.2359  0.0488   0.9611
24      2m     0.0056       0.0747       vader_score  15.3126  1.6594   0.0974
25      3m     0.0017       0.0411  distilbert_score  -0.8642 -0.1982   0.8429
26      3m     0.0017       0.0411         svc_score  -3.4595 -0.6685   0.5040
27      3m     0.0017       0.0411        gbdt_score   6.2813  0.6604   0.5092
28      3m     0.0017       0.0411         knn_score   4.0378  0.8238   0.4103
29      3m     0.0017       0.0411       vader_score   3.5331  0.3297   0.7417

In [11]:
import pandas as pd

df1 = pd.read_csv('../data/News Articles/processed/Bloomberg_with_scores.csv', encoding='ISO-8859-1', index_col='Date')
df1.index = pd.to_datetime(df1.index)
df1 = df1.sort_index()

In [12]:

print(df1.index[0], df1.index[-1])

2006-10-20 20:16:16 2013-11-26 04:51:52